version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: test@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    health_check:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  flaskapp:
    image: vandanapandit/twotierapp:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: test@123
      MYSQL_DB: devops
    ports:
      - "5000:5000"   
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
